### PR TITLE
refactor(server/client): introduce bridge module

### PR DESCRIPTION
**Pull request by mahanmoulaei**
This PR enables integration with other frameworks for ps-mdt. It's currently a work in progress, but 90% of it is complete.

I previously asked about this in Discord but didn't receive a response, so I wanted to ask again. If possible, please pause making any changes to your main repo until I mark this PR as ready-to-review in the next 1-2 days. There are many breaking changes and conflicts that I need to resolve on my end to stay up-to-date with the main repo as I'm refactoring rather than tweaking the code. I see around 10 new commits to the main repo every day, which makes it challenging to resolve conflicts. Thank you for your attention.

### CODE REVIEW

**Comment by xFutte** [comment]
Very very nice! As a small comment, make sure that your updated changes are backward compatible, so people can update their version by pulling the latest version and nothing breaks. Again, very very nice!

**Comment by mahanmoulaei** [comment]
> Very very nice! As a small comment, make sure that your updated changes are backward compatible, so people can update their version by pulling the latest version and nothing breaks. Again, very very nice!

Of course. Before marking this as ready, I'll update everything and ensure that everything is working as it should be.
However, I cannot guarantee that backward compatibility for back-end codes could be achieved easily as around %50 of them if not more are being modified, but I'll try my best. Thanks for your comment!

**Comment by mahanmoulaei** [comment]
This PR is nearly complete! Could I have someone to check all functionality of the script and let me know if something is broken/not working after the code conversion?

**Comment by mahanmoulaei** [comment]
Also, I'm asking the team to review all of my branch code and to specifically look for any comments that start with "CHECK:" and let me know what actions need to be taken with regard to that code...

**Comment by MonkeyWhisper** [comment]
The concept of providing support for ESX makes me seriously reconsider my life decisions. We already have to deal with numerous users who lack even basic understanding of QBCore, and yet they possess a bit more average understanding compared to the ESX users.

**Comment by mahanmoulaei** [comment]
> The concept of providing support for ESX makes me seriously reconsider my life decisions.

Let me know whether you want me to halt the progress because of the ESX users or not...

**Comment by MonkeyWhisper** [comment]
> > The concept of providing support for ESX makes me seriously reconsider my life decisions.
> 
> Let me know whether you want me to halt the progress because of the ESX users or not...

It's a great PR to be passed on just due to this. 

Open a ticket on our Discord, we'll like to discuss further on this

**Comment by mahanmoulaei** [comment]
> Open a ticket on our Discord, we'll like to discuss further on this

I think I'm blind. I couldn't find any ticket-related channel.

**Comment by BackSH00TER** [comment]
> The concept of providing support for ESX makes me seriously reconsider my life decisions. We already have to deal with numerous users who lack even basic understanding of QBCore, and yet they possess a bit more average understanding compared to the ESX users.
I absolutely agree, I think we should refrain from bloating this script with dual support for both ESX and QBCore. It makes maintaining the script that much more difficult, as now anything you add you need to make work for both frameworks and test in both frameworks.

**Comment by MonkeyWhisper** [comment]
Feel free to move all of this into a single repo for mdt.

**Pull request closed without merging**
