### PR TITLE
Moved code to app.js, automatic deletion after 20 minutes, fixed civilians involved

### PR DESCRIPTION
**Pull request by OK1ez**

### CODE REVIEW

**Comment by MonkeyWhisper** [comment]
Hey @OK1ez, this has been tested and working?

**Comment by OK1ez** [comment]
> 

Yep, everything should be working

**Comment by MonkeyWhisper** [comment]
> > 
> 
> Yep, everything should be working

It's been tested on production? i.e, live city?

**Comment by OK1ez** [comment]
> > Yep, everything should be working
> 
> It's been tested on production? i.e, live city?

Just dev server

**Review by MonkeyWhisper — APPROVED** [review]

**Pull request merged**
