### PR TITLE
Plate reader now checks for warrants and returns registered owner and report numbers

### PR DESCRIPTION
**Pull request by nggcasey**
Apologies for the messy 8x commits - Still a bit unfamiliar with github but I'm getting there.

Summary of changes:

1: Updated the plate scanner event "wk:onPlateScanned" in server/main.lua
2: Updated the GetBoloStatus function in server/main.lua to return the BOLO ID and title
3: Created GetWarrantStatus function in server/main.lua to return true/false, owner, and incident ID
4: Added Config.WolfknightNotifyTime = 5000 --How long the notification displays for in miliseconds (30000 = 30 seconds)

**Preview:**

https://www.youtube.com/watch?v=F4H-t9WPUhM&ab_channel=CaseyReed

**1 - Updated the plate scanner event "wk:onPlateScanned" in server/main.lua**

```
if Config.UseWolfknightRadar == true then
	RegisterNetEvent("wk:onPlateScanned")
	AddEventHandler("wk:onPlateScanned", function(cam, plate, index)
		local src = source
		local Player = QBCore.Functions.GetPlayer(src)
		local bolo, title, boloid = GetBoloStatus(plate, title, boloid)
		local warrant, owner, incidentid = GetWarrantStatus(plate, owner, incidentid)

		if bolo == true then
			TriggerClientEvent('QBCore:Notify', src, 'BOLO ID: '..boloid..' | Title: '..title..' | Registered Owner: '..owner..' | Plate: '..plate, 'error', Config.WolfknightNotifyTime)
		end
		if warrant == true then
			TriggerClientEvent('QBCore:Notify', src, 'WANTED - INCIDENT ID: '..incidentid..' | Registered Owner: '..owner..' | Plate: '..plate, 'error', Config.WolfknightNotifyTime)
		end


		if bolo or warrant == true then
		TriggerClientEvent("wk:togglePlateLock", src, cam, true, 1)
		end

	end)
end
```

```
**2: Updated the GetBoloStatus function in server/main.lua to return the BOLO ID and title **

function GetBoloStatus(plate, title, boloid)
    local result = MySQL.query.await("SELECT * FROM mdt_bolos where plate = @plate", {['@plate'] = plate})
	if result and result[1] then
		local title = result[1]['title']
		local boloid = result[1]['id']
		return true, title, boloid
	end

	return false
end
```

**3: Created GetWarrantStatus function in server/main.lua to return true/false, owner, and incident ID**

```
function GetWarrantStatus(plate, owner, incidentid)
    local result = MySQL.query.await("SELECT p.plate, p.citizenid, m.id FROM player_vehicles p INNER JOIN mdt_convictions m ON p.citizenid = m.cid WHERE m.warrant =1 AND p.plate =?", {plate})
	if result and result[1] then
		local citizenid = result[1]['citizenid']
		local Player = QBCore.Functions.GetPlayerByCitizenId(citizenid)
		local owner = Player.PlayerData.charinfo.firstname.." "..Player.PlayerData.charinfo.lastname
		local incidentid = result[1]['id']
		return true, owner, incidentid
	end
	return false
end
```

### CODE REVIEW

**Comment by MonkeyWhisper** [comment]
Has this been tested and fully working? Is this on an active branch located here I can test myself? 

https://github.com/australialiferoleplay/ps-mdt

**Comment by jnccloud** [comment]
> Has this been tested and fully working? Is this on an active branch located here I can test myself?
> 
> https://github.com/australialiferoleplay/ps-mdt

I've been running this PR, but I had to make changes because of a typo I believe. Could probably use further review or I could copy what I used from this and either PR it to @nggcasey's branch or make a new PR and rebase from the latest ps-mdt.

**Comment by MonkeyWhisper** [comment]
> 

Please go ahead and submit the latest correct PR w/o typos. I will merge after that. @nggcasey 

Thanks!

**Comment by MonkeyWhisper** [comment]
> > Has this been tested and fully working? Is this on an active branch located here I can test myself?
> > https://github.com/australialiferoleplay/ps-mdt
> 
> I've been running this PR, but I had to make changes because of a typo I believe. Could probably use further review or I could copy what I used from this and either PR it to @nggcasey's branch or make a new PR and rebase from the latest ps-mdt.

Please go ahead and submit the latest correct PR w/o typos. I will merge after that. @nggcasey @jnccloud 

Thanks!

**Comment by MonkeyWhisper** [comment]
Closing due to answer

**Pull request closed without merging**
