### PR TITLE
Fixed query for missing perms when deleting 

### PR DESCRIPTION
**Pull request by ITKewai**
data was getting deleted even if no permission

### CODE REVIEW

**Comment by ITKewai** [comment]
check if on **QB-Core** you need to move `local src = source` before the query, for some reason source is nil after

**Comment by MonkeyWhisper** [comment]
> check if on **QB-Core** you need to move `local src = source` before the query, for some reason source is nil after

Hi, thanks for sending the PR.

You're the one that submitted the PR, test and let us know else, we'll open an issue and fix it ourselves

**Comment by ITKewai** [comment]
> > check if on **QB-Core** you need to move `local src = source` before the query, for some reason source is nil after
> 
> Hi, thanks for sending the PR.
> 
> You're the one that submitted the PR, test and let us know else, we'll open an issue and fix it ourselves

actually i'm converting the whole script for ESX , i don't use qb 😄

**Comment by MonkeyWhisper** [comment]
Okay, thanks, we don't use ESX.

**Pull request closed without merging**
