### PR TITLE
Idk You able to remove calls from your mdt tablet and will help clear out calls 

### PR DESCRIPTION
**Pull request by MoneSuper**
Please be advised this server sided and will remove the specific call for everyone else after the update their mdt

### CODE REVIEW

**Comment by MoneSuper** [comment]
If you have better method go for it

**Comment by MonkeyWhisper** [comment]
Hey @MoneSuper 

Main reason why we haven't really done this feature is because it can get really confusing when people start removing calls and it also removes for everyone else and then confusing sets in like "what's the latest call?" or "who's removing calls?" 

It will be best permission based for this on a job rank, for dispatch as a Config

**Comment by MoneSuper** [comment]
> 

am waiting for everyone to push the changes then I redo the whole thing 

- Possible making into Dispatch Role? 
- Possible having permission based higher role+

**Comment by MonkeyWhisper** [comment]
Okay! Closing until we get this in order, lots of updates going to dispatch now

**Pull request closed without merging**
