### PR TITLE
Added support for Wolfknight98 Wraith ARS 2X

### PR DESCRIPTION
**Pull request by nggcasey**
Adds support for the Wraith ARS 2x radar.

**IMPORTANT** - Set CONFIG.use_sonorancad = true in the Wraith ARS config.lua otherwise you'll lag out your database.

Credit to QBLes for his assistance!

### CODE REVIEW

**Comment by jnccloud** [comment]
I've been running this PR for 24 hours now. Works great. But  it needs to be a config option so no one inadvertently runs it I think.

**Comment by jnccloud** [comment]
I've been running this PR for 24 hours now. Works great. But  it needs to be a config option so no one inadvertently runs it I think.

**Comment by QBLes** [comment]
> Adds support for the Wraith ARS 2x radar.
> 
> **IMPORTANT** - Set CONFIG.use_sonorancad = true in the Wraith ARS config.lua otherwise you'll lag out your database.

Wonder where you got this code from :P

**Comment by pushkart2** [comment]
> > Adds support for the Wraith ARS 2x radar.
> > **IMPORTANT** - Set CONFIG.use_sonorancad = true in the Wraith ARS config.lua otherwise you'll lag out your database.
> 
> Wonder where you got this code from :P

Is something wrong with this PR ?

**Comment by QBLes** [comment]
> > > Adds support for the Wraith ARS 2x radar.
> > > **IMPORTANT** - Set CONFIG.use_sonorancad = true in the Wraith ARS config.lua otherwise you'll lag out your database.
> > 
> > 
> > Wonder where you got this code from :P
> 
> Is something wrong with this PR ?

No not at all i helped him make it lol

**Comment by NoobySloth** [comment]
Just out of curiosity, what does this do? Looking at adding but want to know before hand. I use the radar.

**Comment by QBLes** [comment]
> Just out of curiosity, what does this do? Looking at adding but want to know before hand. I use the radar.

So when you have the plate checker on if your make a vehicle as stolen it will set off an alarm and lock the plate if it drives past or if you drive past said vehicle.

**Comment by pushkart2** [comment]
The issue is not everyone uses that. So a config option would be better I guess. I am not sure how it works tbh

**Comment by nggcasey** [comment]
> > Adds support for the Wraith ARS 2x radar.
> > **IMPORTANT** - Set CONFIG.use_sonorancad = true in the Wraith ARS config.lua otherwise you'll lag out your database.
> 
> Wonder where you got this code from :P

Yes - Big credit to big Les! Wouldn't have been able to do it without him!

**Comment by nggcasey** [comment]
> The issue is not everyone uses that. So a config option would be better I guess. I am not sure how it works tbh



> The issue is not everyone uses that. So a config option would be better I guess. I am not sure how it works tbh

This commit is just a listener for the event "wk:onPlateScanned", which is an event contained within Wolfknight's radar plate reader script.

If you're not running his radar/plate reader script, this code doesn't get executed.

Wolfknight's radar is also the most commonly used radar script out there. It's free and super comprehensive, and honestly should be part of the qbcore txadmin recipe.

RegisterNetEvent("wk:onPlateScanned")
AddEventHandler("wk:onPlateScanned", function(cam, plate, index)
	local src = source
    local Player = QBCore.Functions.GetPlayer(src)
	local bolo = GetBoloStatus(plate)
	print(cam, plate, index)
	if bolo == true then
		TriggerClientEvent("wk:togglePlateLock", Player.PlayerData.source, cam, beep, bolo)
	end
end)

**Comment by jnccloud** [comment]
> Just out of curiosity, what does this do? Looking at adding but want to know before hand. I use the radar.

Yep.. so as long as you *correctly* add a plate to the MDT under BOLOs, it will sound an alarm just like when you lock a plate using the radar standalone.

**Comment by MonkeyWhisper** [comment]
Okay, 

This is a great tool for cops who RP. 

I will approve this PR with a config option to turn it on and off as well as a small description of what it does on the config file as a comment.

**Comment by nggcasey** [comment]
> Okay,
> 
> This is a great tool for cops who RP.
> 
> I will approve this PR with a config option to turn it on and off as well as a small description of what it does on the config file as a comment.

Added config option

**Pull request merged**
