### PR TITLE
Add Cameras to the MDT

### PR DESCRIPTION
**Pull request by ImXirvin**
This allows police to use the MDT in order to access the cameras from the qb-policejob.

image

### CODE REVIEW

**Comment by NoobySloth** [comment]
Optimized cameras instead of loading individual.
[cameraphotos.zip](https://github.com/Project-Sloth/ps-mdt/files/8880290/cameraphotos.zip)

fxmanifest.lua
```lua
files {
    'ui/**/*.png',
    'ui/**/*.jpg',
    'ui/dashboard.html',
    'ui/dmv.html',
    'ui/bolos.html',
    'ui/incidents.html',
    'ui/penalcode.html',
    'ui/reports.html',
    'ui/warrants.html',
    'ui/app.js',
    'ui/style.css',
}
```
dashboard.html
```html
<div class="cams-container">
                <div class="cams-item">
                    <div class="cams-items" id="1"><img class="cams-image" src="img/cameras/pacific1.png">Pacific Bank CAM 1</div>
                    <div class="cams-items" id="2"><img class="cams-image" src="img/cameras/pacific2.png">Pacific Bank CAM 2</div>
                    <div class="cams-items" id="3"><img class="cams-image" src="img/cameras/pacific3.png">Pacific Bank CAM 3</div>
                    <div class="cams-items" id="4"><img class="cams-image" src="img/cameras/247.png">Limited Ltd Grove St.</div>
                    <div class="cams-items" id="5"><img class="cams-image" src="img/cameras/robs.png">Rob's Liqour Prosperity St.</div>
                    <div class="cams-items" id="6"><img class="cams-image" src="img/cameras/robs.png">Rob's Liqour San Andreas Ave.</div>
                    <div class="cams-items" id="7"><img class="cams-image" src="img/cameras/247.png">Limited Ltd Ginger St.</div>
                    <div class="cams-items" id="8"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Innocence Blvd.</div>
                    <div class="cams-items" id="9"><img class="cams-image" src="img/cameras/robs.png">Rob's Liqour El Rancho Blvd.</div>
                    <div class="cams-items" id="10"><img class="cams-image" src="img/cameras/247.png">Limited Ltd West Mirror Drive</div>
                    <div class="cams-items" id="11"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Clinton Ave</div>
                    <div class="cams-items" id="12"><img class="cams-image" src="img/cameras/247.png">Limited Ltd Banham Canyon Dr</div>
                    <div class="cams-items" id="13"><img class="cams-image" src="img/cameras/robs.png">Rob's Liqour Great Ocean Hwy</div>
                    <div class="cams-items" id="14"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Ineseno Road</div>
                    <div class="cams-items" id="15"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Barbareno Rd.</div>
                    <div class="cams-items" id="16"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Route 68</div>
                    <div class="cams-items" id="17"><img class="cams-image" src="img/cameras/robs.png">Rob's Liqour Route 68</div>
                    <div class="cams-items" id="18"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Senora Fwy CAM 1</div>
                    <div class="cams-items" id="19"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Senora Fwy CAM 2</div>
                    <div class="cams-items" id="20"><img class="cams-image" src="img/cameras/247.png">24/7 Supermarkt Alhambra Dr.</div>
                    <div class="cams-items" id="21"><img class="cams-image" src="img/cameras/fleeca.png">Fleeca Bank Hawick Ave CAM 1</div>
                    <div class="cams-items" id="22"><img class="cams-image" src="img/cameras/fleeca.png">Fleeca Bank Hawick Ave CAM 2</div>
                    <div class="cams-items" id="23"><img class="cams-image" src="img/cameras/fleeca.png">Fleeca Bank Legion Square</div>
                    <div class="cams-items" id="24"><img class="cams-image" src="img/cameras/fleeca.png">Fleeca Bank Del Perro Blvd</div>
                    <div class="cams-items" id="25"><img class="cams-image" src="img/cameras/fleeca.png">Fleeca Bank Great Ocean Hwy</div>
                    <div class="cams-items" id="26"><img class="cams-image" src="img/cameras/paleto.png">Paleto Bank</div>
                    <div class="cams-items" id="27"><img class="cams-image" src="img/cameras/robs.png">Del Vecchio </br> Liquor Paleto Bay</div>
                    <div class="cams-items" id="28"><img class="cams-image" src="img/cameras/247.png">Don's Country Store Paleto Bay CAM 1</div>
                    <div class="cams-items" id="29"><img class="cams-image" src="img/cameras/247.png">Don's Country Store Paleto Bay CAM 2</div>
                    <div class="cams-items" id="30"><img class="cams-image" src="img/cameras/247.png">Don's Country Store Paleto Bay CAM 3</div>
                    <div class="cams-items" id="31"><img class="cams-image" src="img/cameras/vang1.png">Vangelico Jewelery CAM 1</div>
                    <div class="cams-items" id="32"><img class="cams-image" src="img/cameras/vang2.png">Vangelico Jewelery CAM 2</div>
                    <div class="cams-items" id="33"><img class="cams-image" src="img/cameras/vang3.png">Vangelico Jewelery CAM 3</div>
                    <div class="cams-items" id="34"><img class="cams-image" src="img/cameras/vang4.png">Vangelico Jewelery CAM 4</div>
                </div>
            </div>
```

**Comment by JoeSzymkowicz** [comment]
Please make the changes we discussed over Discord and do another push.

**Comment by jnccloud** [comment]
I think those images need to be resized. Each cam photo is 255KB, which doesn't make a lot of sense as they are thumbnails. But great addition I think! 

It would be nice to have a generic cam photo included as well for people who have more cameras setup, but then again that might just fall on the server dev at that point.

Joe, just wondering if you saw my PR for the license/blank profile issue? Curious if you could check it out and see if there's a better way to do it or not.

**Comment by ImXirvin** [comment]
> I think those images need to be resized. Each cam photo is 255KB, which doesn't make a lot of sense as they are thumbnails. But great addition I think!
> 
> It would be nice to have a generic cam photo included as well for people who have more cameras setup, but then again that might just fall on the server dev at that point.
> 
> Joe, just wondering if you saw my PR for the license/blank profile issue? Curious if you could check it out and see if there's a better way to do it or not.

They were already downsized, but yes I dont think It'll hurt to make it smaller.

**Pull request merged**
