### PR TITLE
Plate locking and report IDs for bolos & warrants

### PR DESCRIPTION
**Pull request by nggcasey**
Added plate locking & report IDs for bolos & warrants

### CODE REVIEW

**Comment by MonkeyWhisper** [comment]
Thanks for PR, not merging until defaults values for the convictions are put back as original charges

**Comment by JoeSzymkowiczFiveM** [comment]
Please update this PR for the develop branch

**Comment by nggcasey** [comment]
Done

**Comment by MonkeyWhisper** [comment]
Hi, we will merge but on new UI, please wait until we release it which is coming very soon.

**Pull request closed without merging**
