### PR TITLE
update: enable mdt resize with variables

### PR DESCRIPTION
**Pull request by Spudgun**
Allows users to define the height and width of the mdt whilst also keeping it centered on screen.

Also, combined all the containers into the same code block as there was multiple instances of the same code.

### CODE REVIEW

**Comment by pushkart2** [comment]
Can we have some image or video of whats the purpose of this pr?

**Comment by AMATHSYT** [comment]
ultrawide user here; this would be pretty nice. I've set the content limitations locally.

**Comment by MonkeyWhisper** [comment]
> Allows users to define the height and width of the mdt whilst also keeping it centered on screen.
> 
> Also, combined all the containers into the same code block as there was multiple instances of the same code.

Hi,

What does this do? Is this just to help resize for other resolutions? Like players can do it themselves?

**Comment by Spudgun** [comment]
Incomplete. Advised that the maintainers are looking at doing a UI revamp.

**Pull request closed without merging**
