### PR TITLE
[qb-mdt] - Multiple Fixes/Enhancements

### PR DESCRIPTION
**Pull request by trapw0w**
Fixes some of the issues discussed in #32 

- Add Config option to only show on duty players in the MDT + Remove Players from MDT when going offline, logging out or toggling duty.
- Add support for a firefighter role (note: app.js modifications have been left out as firefighter is not a native QB-Core job, I can add these changes in on request)
- Add callback to DB to match citizenids to player license
- Update toggle duty functionality

This has been tested on a multiplayer server with multiple people. But please note, this has been copy + pasted into Github as my local branch is stored on a Gitlab instance.

### CODE REVIEW

**Comment by IdrisDose** [comment]
Might be best to add an allowed jobs request via a server event versus hard-coding if statements.

**Comment by JoeSzymkowiczFiveM** [comment]
I think the fixes and onduty work is probably good to go, but I cant merge this PR in it's current state due to the new job or the GetCitizenID function code. Instead of that function you should use QBCore.Functions.GetPlayer for the src, which will then make citizenid available, via PlayerData. Regarding the new job, these are customizations we aren't looking to add. If you can make these changes, we can merge this in.

**Comment by trapw0w** [comment]
> Might be best to add an allowed jobs request via a server event versus hard-coding if statements.

I like this idea, much cleaner.


>  but I cant merge this PR in it's current state due to the new job or the GetCitizenID function code. Instead of that function you should use QBCore.Functions.GetPlayer for the src, which will then make citizenid available, via PlayerData.

@JoeSzymkowiczFiveM Please take a look at where this GetCitizenID function is called, it is being called when `QBCore.Functions.GetPlayer` is returning Nil on player drop. Sometimes you will not be able to get the QB-Core player handle once a player disconnects so we must use the FiveM license to match with CitizenIDs in the DB.

**Comment by JoeSzymkowiczFiveM** [comment]
I see now. Thats a clever work-around. Ok lets keep that also.

**Comment by JoeSzymkowiczFiveM** [comment]
I will test this tomorrow. Thank you very much for these key fixes.

**Comment by trapw0w** [comment]
> I will test this tomorrow. Thank you very much for these key fixes.

Just testing the final commit. Sorry about the multiple commits, running a local Gitlab branch so just copy/pasting across to Github. Feel free to squash on merge.

**Comment by JoeSzymkowiczFiveM** [comment]
You're fine. I normally do the same; small, constant checkins. Working on this now.

**Pull request merged**
