### PR TITLE
Fixes Incidents & Convictions Display Issues

### PR DESCRIPTION
**Pull request by LeSiiN**
- some changes to style.css for more space and fully readable words
- changes to app.js for bigger profiles + citizen id + card icon added

### CODE REVIEW

**Review by THE-IV4N — APPROVED** [review]
This fixed the issue of not being able to see the full content of the areas in mdt. 
Before:
Before
After:
After

**Comment by MonkeyWhisper** [comment]
> This fixed the issue of not being able to see the full content of the areas in mdt. Before: Before After: After

Of course it fixes it, that's why we made this PR but this is not the ideal solution.

**Comment by MonkeyWhisper** [comment]
Can you update this PR to this? 

image

**Comment by MonkeyWhisper** [comment]
Thank you! Received on developer branch

**Pull request merged**
