### PR TITLE
Update set radio functionality + show cameraId in the calls sections

### PR DESCRIPTION
**Pull request by BackSH00TER**
# Details
This PR makes two changes, the first adding the cameraId to the call items shown in the MDT and the second updating the "set radio" functionality.

1. Showing cameraId
 - There are two sections where we show the call items. For banks/stores that have cameraIds, this will add the cameraId element to the call item.
From Dashboard:
image
From Map:
image

2. Update set radio functionality
 - This may be a tad bit controversial, so willing to discuss solutions. Currently when you right click on any active unit, you will see the option to Set Radio, however the script will block you from changing other peoples radios and will only let you change your own. 
 - With this change, we are now allowing you to change any active units radio channel on their behalf. We figured this is a useful change so that if you have someone running as a dispatch unit, they can quickly and easily move units to different radio channels while those units are responding to calls. It saves everyone time and makes the dispatch role a bit easier.

### CODE REVIEW

**Comment by nggcasey** [comment]
I like the idea of someone running as dispatch being able to change my radio channel for me.

For example: 

“Traffic 220 this pursuit has entered Sandy Shores can you put me on Channel 2 please”

or

“SWAT 549 can you switch me over to thr TAC channel 3 please”.

Super useful when you are in an action scenario and can’t change the radio channel yourself.

HOWEVER…

There will always be a troll somewhere who might want to switch peoples channels to be an asshole.

Therefore we will need:

1 - A notification msg to the officer whose radio channel was changed saying “Your radio channel was changed by [CALLSIGN][Character First Name/Last Name][Player ID]

2 - Config option to toggle this ability on/off

3 - Config option to rank restrict the ability to change others radio channel

4 - Config option to set which jobs can change channels (i.e. police, ambulance) - We don’t want doj/lawyers being able to do this.

**Comment by MonkeyWhisper** [comment]
> I like the idea of someone running as dispatch being able to change my radio channel for me.
> 
> For example:
> 
> “Traffic 220 this pursuit has entered Sandy Shores can you put me on Channel 2 please”
> 
> or
> 
> “SWAT 549 can you switch me over to thr TAC channel 3 please”.
> 
> Super useful when you are in an action scenario and can’t change the radio channel yourself.
> 
> HOWEVER…
> 
> There will always be a troll somewhere who might want to switch peoples channels to be an asshole.
> 
> Therefore we will need:
> 
> 1 - A notification msg to the officer whose radio channel was changed saying “Your radio channel was changed by [CALLSIGN][Character First Name/Last Name][Player ID]
> 
> 2 - Config option to toggle this ability on/off
> 
> 3 - Config option to rank restrict the ability to change others radio channel
> 
> 4 - Config option to set which jobs can change channels (i.e. police, ambulance) - We don’t want doj/lawyers being able to do this.

This is a great idea. Your security checks are perfect, I would add as well a log to be added to the Staff Logs section of the MDT so all that info can be found on there. 

By the way, thank you for all of these much needed PR improvements, not sure who you're but if you're on our Discord, send me  DM so that I can provide you with a Contributor role for all the recent PRs you have submitted, thank you very much!

**Comment by MonkeyWhisper** [comment]
> # Details
> This PR makes two changes, the first adding the cameraId to the call items shown in the MDT and the second updating the "set radio" functionality.
> 
> 1. Showing cameraId
> 
> * There are two sections where we show the call items. For banks/stores that have cameraIds, this will add the cameraId element to the call item.
>   From Dashboard:
>   image
>   From Map:
>   image
> 
> 2. Update set radio functionality
> 
> * This may be a tad bit controversial, so willing to discuss solutions. Currently when you right click on any active unit, you will see the option to Set Radio, however the script will block you from changing other peoples radios and will only let you change your own.
> * With this change, we are now allowing you to change any active units radio channel on their behalf. We figured this is a useful change so that if you have someone running as a dispatch unit, they can quickly and easily move units to different radio channels while those units are responding to calls. It saves everyone time and makes the dispatch role a bit easier.

Thank you very much for the PRs, much appreciated it. 

By the way, thank you for all of these much needed PR improvements, not sure who you're but if you're on our Discord, send me DM so that I can provide you with a Contributor role for all the recent PRs you have submitted, thank you very much!

**Comment by MonkeyWhisper** [comment]
> I like the idea of someone running as dispatch being able to change my radio channel for me.
> 
> For example:
> 
> “Traffic 220 this pursuit has entered Sandy Shores can you put me on Channel 2 please”
> 
> or
> 
> “SWAT 549 can you switch me over to thr TAC channel 3 please”.
> 
> Super useful when you are in an action scenario and can’t change the radio channel yourself.
> 
> HOWEVER…
> 
> There will always be a troll somewhere who might want to switch peoples channels to be an asshole.
> 
> Therefore we will need:
> 
> 1 - A notification msg to the officer whose radio channel was changed saying “Your radio channel was changed by [CALLSIGN][Character First Name/Last Name][Player ID]
> 
> 2 - Config option to toggle this ability on/off
> 
> 3 - Config option to rank restrict the ability to change others radio channel
> 
> 4 - Config option to set which jobs can change channels (i.e. police, ambulance) - We don’t want doj/lawyers being able to do this.

This is a great idea, people are mischievous and we don't want someone trolling while RPing.  

Your security checks are perfect, I would add as well a log to be added to the Staff Logs section of the MDT so all that info can be found on there.

**Review by MonkeyWhisper — APPROVED** [review]

**Comment by BackSH00TER** [comment]
@nggcasey Good ideas. I'll add these in a followup PR sometime soon

**Pull request merged**
