### PR TITLE
Fix for units not showing in mdt until opened.

### PR DESCRIPTION
**Pull request by cammygames**

### CODE REVIEW

**Review by BackSH00TER — COMMENTED** [review]
This still requires that a player SetsDuty or TogglesDuty in order to show up in the MDT though right? Correct me if I'm wrong, but if a user logs in already clocked in and never touches their duty, they still wouldn't show up?

**Comment by cammygames** [comment]
Yes thats a good shout I hadnt checked this with defaultDuty enabled, I will give it a try and make additional changes

**Comment by cammygames** [comment]
Updated to add it to the loaded event

**Comment by MonkeyWhisper** [comment]
> Updated to add it to the loaded event

Hmm, this is still just looping regardless if they open or not the mdt 

Is this working on a live city?

**Comment by cammygames** [comment]
> > Updated to add it to the loaded event
> 
> Hmm, this is still just looping regardless if they open or not the mdt
> 
> Is this working on a live city?

This is working fine in my test server. What looping are you referring to?

**Comment by MonkeyWhisper** [comment]
> > > Updated to add it to the loaded event
> > 
> > 
> > Hmm, this is still just looping regardless if they open or not the mdt
> > Is this working on a live city?
> 
> This is working fine in my test server. What looping are you referring to?

This function ``HandleDuty`` interferes with qb-core config ``defaultDuty = true,`` https://github.com/qbcore-framework/qb-core/blob/main/shared/jobs.lua#LL21C3-L21C15

Is this live on a server already with players? We need to test this further

**Comment by cammygames** [comment]
This is not on a live server yet, I have added a check to the `OnPlayerLoaded` to stop it firing the event if they aren't on duty at load.

**Comment by MonkeyWhisper** [comment]
As soon as someone loads in, it'll auto clock them in. Many cops that load in aren't on duty right away, this set them on duty as soon as they log in. We should move then event to when they do enter /mdt so that it triggers. 

We are trying to "solve" a non-issue. Units should not show up on mdt until opened because the cops are not on duty yet, by reasoning. 

If anything, we should make an export/event so that it can be added to the clocking for qbcore or something smiliar where they clock in.

**Comment by MonkeyWhisper** [comment]
> This is not on a live server yet, I have added a check to the `OnPlayerLoaded` to stop it firing the event if they aren't on duty at load.

Thank you, I saw that! Great job

**Comment by MonkeyWhisper** [comment]
Hi @cammygames, what do you think about this? 
https://github.com/Project-Sloth/ps-mdt/pull/299#issuecomment-1533850838

**Comment by MonkeyWhisper** [comment]
No response, feel free to reopen if you'd like to discuss

**Pull request closed without merging**
